### ISSUE TITLE
line chart for assets depreciation

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#13]
line chart for assets depreciation

**Comment by ivangarcilazo** [comment]
Hello, I'm getting an error, apparently it's because I start with npm run start:prod.... But the problem is that this script is not there, if I start with another one, I get a connection error.

Also it would be great if you could give me a little more information about the project.

**Comment by bharathkumarchowdary** [comment]
Hi @ivangarcilazo,
Please rebase your branch to master
All the latest code will reflect and the scripts should be visible

**Comment by ivangarcilazo** [comment]
Thanks Bharath!

**Comment by ivangarcilazo** [comment]
Hi, I have everything ready, I just need to add the information to display. Where do I get it from?  I was looking around and I don't know where to get the deprecation of the assets. Thanks for giving me a hand.

**Comment by bharathkumarchowdary** [comment]
you can access from /api/physical_assets/
it will give depreciation percent and depreciation frequency..
If I remember correctly @mohitkhatri06 should've implemented it already
@mohitkhatri06 can you confirm?

**Comment by mohitkhatri06** [comment]
@bharathkumarchowdary I did not implemented the logic.
