### ISSUE TITLE
redesign the navbar with dropdown for calculate

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#143]
We need to modify our navbar need to do some changes, as for now color and font does not matter in the following:

1. make a dropdown named "Calculate" and under that there will be options (EMI, SIP and CAGR) attaching screenshot for reference and here is a site where they used dropdown for reference(https://www.make.com/en)
 
![MicrosoftTeams-image (1)](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/36732f3f-c044-40f7-99c5-40347cdc1f5b)

2. Make the navbar mobile responsive as that should looks like that in navbar as attached in the reference screenshot taken from the (https://www.notion.so/)

![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/6a63f2aa-ada8-4ab6-b7d9-8fe01a546be0)

**Comment by ivangarcilazo** [comment]
Sure, I can do this! Have a nice day :)

**Comment by mohitkhatri06** [comment]
let other navBar options be there don't remove them, let expense and other options be there
