### ISSUE TITLE
Design for the Hero page

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#184]
As for now when user open the web application it redirects the user to the SignUp/Login so we need a Hero Page which will display when user redirected to the first time it will display and if user is already Logged In then it will redirected to home page of the.
**Take care for responsiveness of the Page.**
Design :

Figma : https://www.figma.com/file/CKXkqbkUKY8ZmA1q4yLA3I/Lekka-UI%2FUX?type=design&node-id=0%3A1&mode=design&t=XzuEYq6n4lvGNvZf-1

![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/6602007d-3c81-4b2c-bd5d-2c40248525f0)

**Comment by Rabbok** [comment]
I'd like to work on this issue. Could you please assign it to me?

**Comment by mohitkhatri06** [comment]
May I know your name? @Rabbok

**Comment by Rabbok** [comment]
Maksym Novikov

**Comment by mohitkhatri06** [comment]
please self Assign
