### ISSUE TITLE
Redesign of the NavBar/Header

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#185]
As for now need to redesign the navBar as the given 

Figma:
https://www.figma.com/file/CKXkqbkUKY8ZmA1q4yLA3I/Lekka-UI%2FUX?type=design&node-id=0%3A1&mode=design&t=XzuEYq6n4lvGNvZf-1

Take care for responsiveness of the design.

**Comment by BeteabAdmassu** [comment]
Hi there! I've seen the request to redesign the NavBar/Header, and I'm ready to take on this task.
