### ISSUE TITLE
income statement new design from figma

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#186]
Create the Income statement page design as given in the figma link. Focus on responsiveness and look. Nav bar at the top is out of the following task.

![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/1ee1e71c-4b85-4a1c-80b7-741ff1a97a34)

Figma : https://www.figma.com/file/CKXkqbkUKY8ZmA1q4yLA3I/Lekka-UI%2FUX?type=design&node-id=0%3A1&mode=design&t=XzuEYq6n4lvGNvZf-1

**Comment by Jpalsana07** [comment]
hello
