### ISSUE TITLE
If logged in then redirect to home instead of the signin

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#195]
A user is logged in and try to route "/singin" or "/singup" from the address bar he/she should redirected to home page because he is already logged in. 

And there is unused component there which is confusing the developer  look if it is useful or not if not useful please remove.
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/80978569-0571-4dca-9a30-13b4e0a36917)

**Comment by ivangarcilazo** [comment]
Can I assign this problem to myself? Do you have to set the data in the local session or have you done it? I am interested!
