### ISSUE TITLE
Update the end points of the tag

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#202]
As few backend api end points are updated for the "tag" please update those wherever they are in use. Make sure test all api works as previously it was, without any network error

These tags are mostly are at Expenes page

![MicrosoftTeams-image (2)](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/6940f929-817b-4b0d-8660-33b5f443b51a)

**Comment by BeteabAdmassu** [comment]
I'm ready to take on this task.
