### ISSUE TITLE
create the goals page with the endpoints

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#205]
one developer previously done work  on the following issue ,existing PR : https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/91

need to add end points so we can work do the goals CURD.

https://api.finuncle.com/swagger/

![MicrosoftTeams-image (3)](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/0c63446b-062d-41bc-8938-40e605784def)

**Comment by ivangarcilazo** [comment]
Excelent1Maybe if you have some design mockup I can make it from 0 all over again, to have the whole structure more organized, but I continue this one or make a new one without so much design.

**Comment by bharathkumarchowdary** [comment]
@ivangarcilazo , Please continue with whatever is present. We can see the design part later

**Comment by bharathkumarchowdary** [comment]
@ivangarcilazo , Sorry for confusion, I saw the design in figma just now.. It looks good to go.. develop according to figma designs

**Comment by mohitkhatri06** [comment]
@ivangarcilazo  lets continue with the existing design, whatever is present
