### ISSUE TITLE
Add calculator icon on the NavBar

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#207]
As previously as we have a dropdown for the calculator add  one icon so when user click on this icon it shows all calculators and one more click on the icon close the dropdown or anywhere click on the screen close dropdown, 

Example : as in website of LinkedIn when we click on the user profile icon it at the extreme right shows dropdown.

icon : https://www.flaticon.com/free-icon/calculator_2374409?related_id=2374367&origin=search

**Comment by BeteabAdmassu** [comment]
I'm ready for the task.
