### ISSUE TITLE
SIP and CAGR Calculators

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#212]
SIP and CAGR Calculators need a share option similar to EMI calculator
CAGR Calculator should

- Show absolute returns along with CAGR returns as a percentage number and absolute value
- Show a bar graph with the value for each year

**Comment by rockingrohit9639** [comment]
@mohitkhatri06 assign this to me

**Comment by rockingrohit9639** [comment]
@bharathkumarchowdary Can you please clarify how can we calculate the values for each year to show in the bar graph?

**Comment by bharathkumarchowdary** [comment]
Go to this site.. and calculate CAGR.. it will show bar graph if you scroll down
https://cagrcalculator.net/result/

there are bar graph and pie chart in it.. try to do the same in our site too with the style matching our own

@mohitkhatri06 .. do we have centralised style assets for each kind of chart?

**Comment by mohitkhatri06** [comment]
We can make centralised them, right now we don't have
