### ISSUE TITLE
fix some minor issues at login and signup

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#225]
1. add padding at the text boxes
2. add and modify  link for T and C and privacy policy
3.  add some input validation for clint side
4.  remember me
5.  password eye to see password

**Comment by bharathkumarchowdary** [comment]
better to have a switch in code to hide the social media login buttons (since they are not yet implemented)

**Comment by rockingrohit9639** [comment]
I am working on this issue.
