### ISSUE TITLE
add new support page 

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#233]
Right there no support page there 
need to add a option at the top of the navbar so user can go to the support page:
https://www.figma.com/file/HZBMEXvoJCZISqAiyYivFz/Lekka-UI%2FUX-Designs?type=design&node-id=219-1329&mode=design

**Comment by tanvirAR** [comment]
Do I need to convert the login page ?

**Comment by deepansh946** [comment]
@mohitkhatri06 Assign this to me.
