### ISSUE TITLE
add footer at the Hero page and common font family

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#241]
1. there is no footer at hero page add footer
2.  add same color to the footer also which is given in figma
3. use the same font family in entire webapp which is mentioned in figma

**Comment by ivangarcilazo** [comment]
Can you provide me the figma ? Or in wich part of Asana can find it? Thanks Mohit.

**Comment by ivangarcilazo** [comment]
It only lets me do squash and merge :c

**Comment by mohitkhatri06** [comment]
done
