### ISSUE TITLE
Add budget at expense page for CURD

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#244]
Right now there is no ui for setting the budget.  Implement that with CURD

![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/d6c9150c-e539-42bd-aa1d-1a7357b375d9)

at 1. instead of the textbox we need to show the Current month budget with month name and amount 
at 2. show all budget viewAll it will popup a list of previous budgets
when click on set budget, modal should show the Amount, month with year selection.

**Comment by rockingrohit9639** [comment]
@mohitkhatri06 I can take this one
