### ISSUE TITLE
Add a card view or widget for budget at home screen

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#245]
At home  screen add a card or widget as following:

![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/4f2a13c0-70ff-4c5c-84be-fdf4b2b6faa5)

sum up the expenses by month and subtract it from the budget to get the remaining

**Comment by chahat151** [comment]
As per discussion with @mohitkhatri06, I'll be working on this issue.
