### ISSUE TITLE
Make Calculators descriptive

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#272]
- Add help content to mouse hover or button click on help symbol for each field in all calculators
- Add a couple of paragraphs explaining what the calculation is and a formula with an example
- [x] Load all calculators with some default values when the page is loaded
- [x] All calculators should have share option similar to EMI calculator

**Comment by mohitkhatri06** [comment]
@bharathkumarchowdary for the last 2 points,  present calculator has this share feature with them like emi, and all calculator are having a default value in the initial

**Comment by nanipunepalle** [comment]
assign it to me @mohitkhatri06
