### ISSUE TITLE
User Email Verification

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#276]
A user's email must be verified for authenticity

Email verification with the use of POST to a backend endpoint from api.finuncle.com/swagger

request Body : 
```
{
"user_email" : "example@gmail.com"
}
```

redirection of the mail : https://www.finuncle.com/users/api/users/activate/5/bx77

![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/8872935/6c775980-8b3d-4ab3-a809-f346c513848c)

**Comment by ivangarcilazo** [comment]
Can i take this issue? 
This should be after registration?

**Comment by nanipunepalle** [comment]
@mohitkhatri06  assign it to me

**Comment by imhardikdesai** [comment]
please assign this to me
