### ISSUE TITLE
Update the end points to the version1

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#287]
**Is your feature request related to a problem? Please describe.**
Need to  update end points to v1

**Describe the solution you'd like**
Use the swagger for reference and test each point which are ready to update

**Describe alternatives you've considered**
NA

**Additional context**
https://api.finuncle.com/swagger/

**Comment by rockingrohit9639** [comment]
@mohitkhatri06 can you assign this to me ?

**Comment by mohitkhatri06** [comment]
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/702aeba0-90b9-4857-b8f1-6b29b378af0b)
