### ISSUE TITLE
Delete Account Option

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#288]
**Is your feature request related to a problem? Please describe.**
A user should have a delete account option in user settings or account page

**Describe the solution you'd like**
delete account button. After this action a new user with this email or username should be able to signup afresh

**Describe alternatives you've considered**
No alternative

**Additional context**
NA

**Comment by ivangarcilazo** [comment]
Can I take this issue ?

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/421
