### ISSUE TITLE
Production build warning

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#317]
**Describe the bug**
build script giving a warning about babel

**To Reproduce**
npm run build:prod

**Expected behavior**

**Screenshots**
 npm run build:prod
  shell: /usr/bin/bash -e {0}
  
> finuncle-app@1.0.0 build:prod
> env-cmd -f ./environments/.prod.env craco build
Creating an optimized production build...
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.
babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by imhardikdesai** [comment]
@mohitkhatri06 Can You assign this to me, I wont to work on this

**Comment by bharathkumarchowdary** [comment]
build is not passing

**Comment by bharathkumarchowdary** [comment]
npm install mistake.. build is actually passing
