### ISSUE TITLE
Make the landing page Navbar responsive

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#323]
**Is your feature request related to a problem? Please describe.**
Right now the landing page is not responsive and it is not looking good in mobile devices 

**Describe the solution you'd like**
make the Navbar responsive and add a dropdown for the calculators 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by imhardikdesai** [comment]
@mohitkhatri06 Can you assign this to me, i won't to work on this
