### ISSUE TITLE
Feedback should work when user is not authenticated

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#324]
**Describe the bug**
For the feedback no token is not needed becuase we already taking the user email and name.

**To Reproduce**
1. Go to the site and do logout 
2. Click on leave feedback at the bottom,
3.  fill the form and See error

**Expected behavior**
feedback should submit the data when user is logged in and logged out

**Screenshots**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by ivangarcilazo** [comment]
Maybe this is giving a backend error ? 401 specifically, I think the backend should configure that part.

**Comment by ivangarcilazo** [comment]
Or do you mean that only authorized persons can send feedback? Because in the frontend payload the necessary data is loaded :0

**Comment by mohitkhatri06** [comment]
Both user should be able to send the feeeback no auth token needed

**Comment by ivangarcilazo** [comment]
Sure, but the backend returns 401, so it is the backend that is requesting it.

**Comment by ivangarcilazo** [comment]
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/105944413/64bfe92e-283e-4164-8344-6885ddef5f96)

![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/105944413/9619470f-b3a3-4f18-afa5-96bc4b8fa48b)


The payload has no token

**Comment by ivangarcilazo** [comment]
Or maybe I'm making a mistake

**Comment by mohitkhatri06** [comment]
This is the bug which we need to resolve, the error 401 is coming becuase we have a token attached with the feedback request which is not needed, other wise backend is working correctly here is the parameters which feedback needed https://api.finuncle.com/api/feedback/

**Comment by ivangarcilazo** [comment]
Oh okay, i understand now. Thanks

**Comment by ivangarcilazo** [comment]
Now it's working, with all 😮

**Comment by bharathkumarchowdary** [comment]
@mohitkhatri06 , do you want to assign to someone else? Please proceed!

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/356 raised the PR
