### ISSUE TITLE
 sign in or sign up validation error

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#329]
**Describe the bug**
While sign in or up there is form validation error is showing up even when the user already filled the required details

**To Reproduce**
1. Go to sign in and enter details with wrong password and after that correct the passwrd and submit again it will show a validation error stating that username is required 

**Expected behavior**
Should not give error if field is not empty

**Screenshots**
NA

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
NA

**Comment by rockingrohit9639** [comment]
@mohitkhatri06

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/330
