### ISSUE TITLE
Published links for calculations crash

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#336]
**Describe the bug**
I published links for some calculations I did with our EMI calculator long ago. Now I clicked the link again, it crashes and shows 404 page according to screenshot. Links for calculations should be long lasting. Any kind of dev activity should not disturb them. We should solve this and also add a unit test and a browser level e2e test for this

**To Reproduce**
1. Go to ['emi calculation'](https://finuncle.com/loan_emi_calculator?loan_principal=1000000&loan_interest=12&loan_tenure=36&emi_day=5&disbursement_date=2023-09-23)
2. See error

**Expected behavior**
EMI Calculation should show up

**Screenshots**
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/8872935/2f79961e-c288-411a-84f0-b1bdd0825ea1)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari
 - Version 17

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mohitkhatri06** [comment]
@bharathkumarchowdary this is an excepted behavior as we updated the routes in the webapp, these were updated at the time of migration to TS. As you can see that the routes and parameters names are updated

**New**
https://finuncle.com/emi-calculator?loanPrincipal=1795000&loanInterest=11&loanTenure=3&emiDay=5&disbursementDate=1699378632

 **Old**
https://finuncle.com/loan_emi_calculator?loan_principal=1000000&loan_interest=12&loan_tenure=36&emi_day=5&disbursement_date=2023-09-23

**Comment by mohitkhatri06** [comment]
There is bug in the date for the new URL so need to fix that

**Comment by bharathkumarchowdary** [comment]
Add one unit test to check calculators share link works
