### ISSUE TITLE
handle the 500 server error for the end points

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#343]
**Describe the bug**
Right now if error 500 is happening there is no proper way to notify the user about the error for example

https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/63dc1e0f-0633-49d1-a0c3-2a0da3a8188b

**To Reproduce**
1. Go to 'signup page'
2.Enter the details and submit
3. See error

**Expected behavior**
There should be a proper notification to the user about the error

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
NA

**Comment by imhardikdesai** [comment]
@mohitkhatri06 please assign this to me
