### ISSUE TITLE
Add utils indicator for the Rupees

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#352]
**Is your feature request related to a problem? Please describe.**
There should be Indian standard indication of the rupees instead of million and billions, use Lakhs, crores. There is already exiting function in util.js
-> set the max limits in calulators

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by imhardikdesai** [comment]
Hello @mohitkhatri06 please assign this to me

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/524
