### ISSUE TITLE
Add a new dropdown at Navbar the features/tools

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#357]
**Is your feature request related to a problem? Please describe.**
add a feature/tool option to show all the show the all tools/feature
features need to add:
friendly dashboard
expense and budget visuals and graph feature
goals for outstanding's and interests
balance sheet and charts
Income and expenses 
different calculators  

**Describe the solution you'd like**
screenshot for reference
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/27a6914d-5b1d-49f9-b127-d21dbcc4a1ba)

After clicking the particular feature or tool it should open that feature detail's how we are providing the solutions to the user

**Describe alternatives you've considered**
NA

**Additional context**
https://cleartax.in/

**Comment by imhardikdesai** [comment]
@mohitkhatri06 i would like to work on this, please assign this to me

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/380
