### ISSUE TITLE
Calculators download calculations csv sheet

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#363]
**Is your feature request related to a problem? Please describe.**
In all of the calcualaors (EMI, SIP, XIRR), we need to be able to export the calculations as a csv file to be downloaded by customer

**Comment by nanipunepalle** [comment]
@mohitkhatri06  assign it to me

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/366
