### ISSUE TITLE
Handle Decimal Point in Money

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#391]
**Describe the bug**
When you create an expense with the value 717.3333333333334, the server comes up with a response "Ensure that there are no more than 2 decimal places.". This error must be handled in frontend by either recreating the expense with a rounded up value or prevent the error by handling all expense values rounding off to 2 decimal places

**To Reproduce**
create an expense with amount 717.3333333333334 either with Ui or excel. I tested with excel

**Expected behavior**
create an expense with 717.3333333333334 value or 717.33 rupees

**Screenshots**
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/8872935/338f5bea-b507-421b-a325-6be229c2ae7d)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
Not a smartphone. It is on Google chrome on macOS PC with Safari browser

**Additional context**
NA

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/393
