### ISSUE TITLE
Expenses UI select multiple add tag

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#401]
**Is your feature request related to a problem? Please describe.**
I can't select multiple expenses and add one tag to all of them

**Describe the solution you'd like**
select multiple expenses and add one tag to all of them

**Describe alternatives you've considered**
select each expense and add tag

**Additional context**
https://github.com/shadcn-ui/ui/issues/66
In jsx code we previously had the following file where user were able to search and create the tag if it doesn't exist here is the code,
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/196a7a96-53fc-4fbd-9f1e-00baf96e9528)

**Comment by imhardikdesai** [comment]
@mohitkhatri06 assign this to me

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/413
