### ISSUE TITLE
Bugs on the budget chart

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#402]
**Describe the bug**
Here is few bugs
1. remove the NaN
2.  use isFixed(2)
3.  those dropdown should work in the budget for duration

**To Reproduce**
go to Dashboard

**Expected behavior**

**Screenshots**
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/5f349f9f-51f4-456f-9fa9-2cd2914e7848)

**Additional context**

**Comment by Santohack** [comment]
hi
