### ISSUE TITLE
No Uniqueness in Favicon

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#415]
**Describe the bug**
Favicon of the site is generic, and not related to Finuncle 

**To Reproduce**
Open finuncle.com
Look at the icon on tab

**Expected behavior**
Finuncle should have a unique favicon. Better to use the logo designed by @rockingrohit9639 for android app

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/421
