### ISSUE TITLE
Dropdown for the Income and Expense Statement

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#436]
right now the drop down of the income and expense is hardcoded need to take those from the following end points:

http://api.finuncle.com/api/v1/income_source_type
http://api.finuncle.com/api/v1/income_expense_type

**Comment by nanipunepalle** [comment]
@mohitkhatri06 assign it to me

**Comment by nanipunepalle** [comment]
#450
