### ISSUE TITLE
Add Expense dialog acknowledgements 

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#46]
Add Expense dialog box should show acknowledgement to user after doing following actions

- Added new individual expense
- Added expenses via excel

After pressing delete expense from the list, the UI should pop-up for user confirmation

We should use https://sweetalert.js.org/guides/ for this task.

**Comment by mohitkhatri06** [comment]
@ivangarcilazo  you can use https://sweetalert.js.org/guides/ while you start working on it.
