### ISSUE TITLE
Lending Page Improvements

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#466]
**Describe the solution you'd like**
Lending Page needs to have following improvements 
- pie chart should have all small numbers combined into others category as is done in chart's legend
- In Add transaction form, 
    - Lending Account selector should close after selecting an account 
    - Principal Amount field label should change to "Amount" if account is not new
    - Date should be pre-filled with today
    - rename Choose the date to Date
    - payment method must be selectable not text input

**Comment by imhardikdesai** [comment]
@mohitkhatri06 @bharathkumarchowdary  please assign this to me

**Comment by imhardikdesai** [comment]
Hello @bharathkumarchowdary ,
for this point - payment method must be selectable not text input
backend had any enum values for the post?

**Comment by Nikhilcs36** [comment]
> > Hello @bharathkumarchowdary , for this point - payment method must be selectable not text input backend had any enum values for the post?
> 
> @Nikhilcs36, do we have any endpoint for it?

yes , http://127.0.0.1:8000/api/v2/payment_methods

**Comment by bharathkumarchowdary** [comment]
> > > Hello @bharathkumarchowdary , for this point - payment method must be selectable not text input backend had any enum values for the post?
> > 
> > 
> > @Nikhilcs36, do we have any endpoint for it?
> 
> yes , http://127.0.0.1:8000/api/v2/payment_methods

@imhardikdesai , Is this enough?

**Comment by Nikhilcs36** [comment]
> > > > Hello @bharathkumarchowdary , for this point - payment method must be selectable not text input backend had any enum values for the post?
> > > 
> > > 
> > > @Nikhilcs36, do we have any endpoint for it?
> > 
> > 
> > yes , http://127.0.0.1:8000/api/v2/payment_methods
> 
> @imhardikdesai , Is this enough?

need some modification in this endpoint for fetching dropdown value.
