### ISSUE TITLE
Notifications component

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#50]

**Comment by realrohitgurav** [comment]
Can you give more details as to what the issue is? :)

**Comment by bharathkumarchowdary** [comment]
The Header of the website needs a notifications component in REACT

- It should continuously (once every 2 seconds) check REST API server for any new notification for user
- It should alert user for notifications
- Should show 3 notifications upon clicking the button, and should be scrollable
- Each notification item should have a prop: is_seen. The styling for item should change with this prop

API endpoint is not up yet.. Till then development can be done with mock data hardcoded

**Comment by mohitkhatri06** [comment]
updated new issue : https://github.com/GVR-Secure-Solutions/lekkalu-frontend/issues/170
