### ISSUE TITLE
Comparison Results doesn't contain all scenarios

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#515]
**Describe the bug**
When an unauthenticated user is trying to load a comparison by link, and presses simulate button, and if there are multiple scenarios in the comparison, we only see one line in the graph. Upon pressing simulate button multiple times, this problem is getting fixed

**To Reproduce**
1. Go to http://localhost:3000/comparisons/11 after starting local server
2. Click on Simulate button on top
3. Even though loaded are 2 scenarios, for the first couple of times of clicking simulaiton button, you will se only one line in the graph

**Expected behavior**
All scenarios in a comparison should have a line in the graph of comparison's simulation results

**Screenshots**
![Screenshot 2024-04-10 at 6 02 11 PM](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/8872935/ee951244-a97c-4393-9658-15884ce62aa2)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 119.0.6045.159 (Official Build) (arm64)

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by mohitkhatri06** [comment]
@Sandip-Z 

http://localhost:3000/comparisons/28

The above comparison is from the "reacter" user . there is one undefined call is happening due to this data is not loading

https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/9ee79354-4639-4002-acc9-67da42e4d2c7

**Comment by Sandip-Z** [comment]
@mohitkhatri06, while developing the this feature, some scenarios were created without goals. The "undefined" you mentioned is the API request to those goals in scenario.
This issue shouldn't exist in newly created scenarios.
