### ISSUE TITLE
expenses POST not rounding number

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#526]
**Describe the bug**
when sending expense entry to api endpoint /v1/expenses/ via POST request, frontend is not rounding the digits to 2 decimal places

example data for post request: {"amount":1624.3333333333333,"tags":[26,26],"time":"2023-01-18T18:30:00.000Z"}

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/532
