### ISSUE TITLE
description and show the details of the scenarios and comparison for feature page

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-frontend#537]
for the features we need to show scenarios also
![image](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/7581bf14-61df-4978-b73a-9a202e165b16)

**Comment by Sandip-Z** [comment]
@bharathkumarchowdary Lets decide the content of the page and the description to show in this menu.

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z , you can begin with your understanding, we'll correct if the interpretation is wrong with reviews
