### ISSUE TITLE
Lending Transaction Payment method (Add or Edit not working)

### ISSUE THREAD

**Issue by imhardikdesai** [GVR-Secure-Solutions/lekkalu-frontend#575]
**Describe the bug**
When adding or edition payment methods in lending account's transaction then it shows invalid payment_method type from API. we need to send correct values from frontend so backend can accept it

**To Reproduce**
1. Go to https://finuncle.com/lending
2. Click on add transaction
3. click on advance option, where you can find payment method option
4. See error in inspect, from API

**Expected behavior**
Payment method value should be sent correctly

UPI
Card
NetBanking
Cash

above values should be sent to backend

**Screenshots**
<img width="1335" alt="image" src="https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/87645745/a73c4760-070f-4c9e-a9e6-64c3b9e0b806">

**Comment by URVESH1121** [comment]
![Screenshot from 2024-06-13 23-24-19](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/83448942/14e5e376-6c40-4c6c-8eaf-cadfa784d57c)
It works now. Can you elaborate more?

**Comment by imhardikdesai** [comment]
At the add transaction time, it now throwing any error and also not saving payment method + reference no.
but after transaction created if you try to update it then it throws error fro payment method

@mohitkhatri06 @URVESH1121
