### ISSUE TITLE
Improve error handling when logging in

### ISSUE THREAD

**Issue by ivangarcilazo** [GVR-Secure-Solutions/lekkalu-frontend#90]
Improve error handling, as well as display the problem occurred.
For example: When an incorrect password is entered, display it as a modal. Consider the UI for the problem in question.

**Comment by Himanshu-Khanna** [comment]
Hey I would like to contribute to this could you please assing it to me

**Comment by bharathkumarchowdary** [comment]
Sure.. Please go ahead..
I will remove current assignment, and you're free to contribute

**Comment by mohitkhatri06** [comment]
done
