### ISSUE TITLE
Expense page pagination

### ISSUE THREAD

**Issue by bharathkumarchowdary** [GVR-Secure-Solutions/lekkalu-frontend#92]
Expense page pagination shows 70 pages for any number of expenses existing
For example, if the expenses that are available in backend are only 5, it still shows 1 - 10 of 70

**Comment by mohitkhatri06** [comment]
The existing pagination is not working as expected, after uploading the expenses sheet xlsx file also.

**Comment by ivangarcilazo** [comment]
I've a doubt, if are changes on the ui of the pages of expenses, i make that thinking about the new design?

**Comment by mohitkhatri06** [comment]
@ivangarcilazo let's leave this one till edwin's filtering thing is completed, as for now we should focus on the pagination.

**Comment by ivangarcilazo** [comment]
So we wait for Edwin to finish with the filtering to continue with this one?

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/issues/227
